# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: "windows-latest"

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: build
	Dockerfile: 
	buildContext: 
	
stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: Build
    displayName: Build all images
    steps:  
    - task: DockerCompose@0
      inputs:
        dockerComposeFile: 'docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
		
		
		
		https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops
		
		https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#build-service-images